/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerUpdateProfileRouteImport } from './routes/seeker/update-profile'
import { Route as SeekerSavedJobsRouteImport } from './routes/seeker/saved-jobs'
import { Route as SeekerProfileRouteImport } from './routes/seeker/profile'
import { Route as SeekerPaymentsRouteImport } from './routes/seeker/payments'
import { Route as SeekerDashboardRouteImport } from './routes/seeker/dashboard'
import { Route as SeekerBrowseJobsRouteImport } from './routes/seeker/browse-jobs'
import { Route as SeekerApplicationsRouteImport } from './routes/seeker/applications'
import { Route as EmployerPaymentsRouteImport } from './routes/employer/payments'
import { Route as EmployerJoblistRouteImport } from './routes/employer/joblist'
import { Route as EmployerDashboardRouteImport } from './routes/employer/dashboard'
import { Route as EmployerApplicationsRouteImport } from './routes/employer/applications'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerUpdateProfileRoute = SeekerUpdateProfileRouteImport.update({
  id: '/seeker/update-profile',
  path: '/seeker/update-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerSavedJobsRoute = SeekerSavedJobsRouteImport.update({
  id: '/seeker/saved-jobs',
  path: '/seeker/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerProfileRoute = SeekerProfileRouteImport.update({
  id: '/seeker/profile',
  path: '/seeker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerPaymentsRoute = SeekerPaymentsRouteImport.update({
  id: '/seeker/payments',
  path: '/seeker/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerDashboardRoute = SeekerDashboardRouteImport.update({
  id: '/seeker/dashboard',
  path: '/seeker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerBrowseJobsRoute = SeekerBrowseJobsRouteImport.update({
  id: '/seeker/browse-jobs',
  path: '/seeker/browse-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerApplicationsRoute = SeekerApplicationsRouteImport.update({
  id: '/seeker/applications',
  path: '/seeker/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPaymentsRoute = EmployerPaymentsRouteImport.update({
  id: '/employer/payments',
  path: '/employer/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJoblistRoute = EmployerJoblistRouteImport.update({
  id: '/employer/joblist',
  path: '/employer/joblist',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/employer/applications',
  path: '/employer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/playground': typeof PlaygroundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/joblist': typeof EmployerJoblistRoute
  '/employer/payments': typeof EmployerPaymentsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/browse-jobs': typeof SeekerBrowseJobsRoute
  '/seeker/dashboard': typeof SeekerDashboardRoute
  '/seeker/payments': typeof SeekerPaymentsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved-jobs': typeof SeekerSavedJobsRoute
  '/seeker/update-profile': typeof SeekerUpdateProfileRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/playground': typeof PlaygroundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/joblist': typeof EmployerJoblistRoute
  '/employer/payments': typeof EmployerPaymentsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/browse-jobs': typeof SeekerBrowseJobsRoute
  '/seeker/dashboard': typeof SeekerDashboardRoute
  '/seeker/payments': typeof SeekerPaymentsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved-jobs': typeof SeekerSavedJobsRoute
  '/seeker/update-profile': typeof SeekerUpdateProfileRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/playground': typeof PlaygroundRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/joblist': typeof EmployerJoblistRoute
  '/employer/payments': typeof EmployerPaymentsRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/browse-jobs': typeof SeekerBrowseJobsRoute
  '/seeker/dashboard': typeof SeekerDashboardRoute
  '/seeker/payments': typeof SeekerPaymentsRoute
  '/seeker/profile': typeof SeekerProfileRoute
  '/seeker/saved-jobs': typeof SeekerSavedJobsRoute
  '/seeker/update-profile': typeof SeekerUpdateProfileRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/playground'
    | '/auth/login'
    | '/auth/register'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/joblist'
    | '/employer/payments'
    | '/seeker/applications'
    | '/seeker/browse-jobs'
    | '/seeker/dashboard'
    | '/seeker/payments'
    | '/seeker/profile'
    | '/seeker/saved-jobs'
    | '/seeker/update-profile'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/playground'
    | '/auth/login'
    | '/auth/register'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/joblist'
    | '/employer/payments'
    | '/seeker/applications'
    | '/seeker/browse-jobs'
    | '/seeker/dashboard'
    | '/seeker/payments'
    | '/seeker/profile'
    | '/seeker/saved-jobs'
    | '/seeker/update-profile'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/playground'
    | '/auth/login'
    | '/auth/register'
    | '/employer/applications'
    | '/employer/dashboard'
    | '/employer/joblist'
    | '/employer/payments'
    | '/seeker/applications'
    | '/seeker/browse-jobs'
    | '/seeker/dashboard'
    | '/seeker/payments'
    | '/seeker/profile'
    | '/seeker/saved-jobs'
    | '/seeker/update-profile'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  PlaygroundRoute: typeof PlaygroundRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  EmployerApplicationsRoute: typeof EmployerApplicationsRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerJoblistRoute: typeof EmployerJoblistRoute
  EmployerPaymentsRoute: typeof EmployerPaymentsRoute
  SeekerApplicationsRoute: typeof SeekerApplicationsRoute
  SeekerBrowseJobsRoute: typeof SeekerBrowseJobsRoute
  SeekerDashboardRoute: typeof SeekerDashboardRoute
  SeekerPaymentsRoute: typeof SeekerPaymentsRoute
  SeekerProfileRoute: typeof SeekerProfileRoute
  SeekerSavedJobsRoute: typeof SeekerSavedJobsRoute
  SeekerUpdateProfileRoute: typeof SeekerUpdateProfileRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/update-profile': {
      id: '/seeker/update-profile'
      path: '/seeker/update-profile'
      fullPath: '/seeker/update-profile'
      preLoaderRoute: typeof SeekerUpdateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/saved-jobs': {
      id: '/seeker/saved-jobs'
      path: '/seeker/saved-jobs'
      fullPath: '/seeker/saved-jobs'
      preLoaderRoute: typeof SeekerSavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/profile': {
      id: '/seeker/profile'
      path: '/seeker/profile'
      fullPath: '/seeker/profile'
      preLoaderRoute: typeof SeekerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/payments': {
      id: '/seeker/payments'
      path: '/seeker/payments'
      fullPath: '/seeker/payments'
      preLoaderRoute: typeof SeekerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/dashboard': {
      id: '/seeker/dashboard'
      path: '/seeker/dashboard'
      fullPath: '/seeker/dashboard'
      preLoaderRoute: typeof SeekerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/browse-jobs': {
      id: '/seeker/browse-jobs'
      path: '/seeker/browse-jobs'
      fullPath: '/seeker/browse-jobs'
      preLoaderRoute: typeof SeekerBrowseJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/applications': {
      id: '/seeker/applications'
      path: '/seeker/applications'
      fullPath: '/seeker/applications'
      preLoaderRoute: typeof SeekerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/payments': {
      id: '/employer/payments'
      path: '/employer/payments'
      fullPath: '/employer/payments'
      preLoaderRoute: typeof EmployerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/joblist': {
      id: '/employer/joblist'
      path: '/employer/joblist'
      fullPath: '/employer/joblist'
      preLoaderRoute: typeof EmployerJoblistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/employer/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  PlaygroundRoute: PlaygroundRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  EmployerApplicationsRoute: EmployerApplicationsRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerJoblistRoute: EmployerJoblistRoute,
  EmployerPaymentsRoute: EmployerPaymentsRoute,
  SeekerApplicationsRoute: SeekerApplicationsRoute,
  SeekerBrowseJobsRoute: SeekerBrowseJobsRoute,
  SeekerDashboardRoute: SeekerDashboardRoute,
  SeekerPaymentsRoute: SeekerPaymentsRoute,
  SeekerProfileRoute: SeekerProfileRoute,
  SeekerSavedJobsRoute: SeekerSavedJobsRoute,
  SeekerUpdateProfileRoute: SeekerUpdateProfileRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
